### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by BegBlev** [bubux29/snsm#1]
Bonjour bubux29,

Je fais mois aussi partie de la SNSM et je souhaiterai rentrer en contact avec toi.

Voici mon mail:
begblev arobase laposte point net

A+ j'espère.
Vince

**Comment by bubux29** [comment]
Salut,

J'ai tenté de te contacter par MP... Pas de réponse pour l'instant.

Tiens-moi au jus
Sylvain

**Comment by bubux29** [comment]
Re,
Bon, j'ai répondu à ta réponse... il faudra que tu jettes encore un oeil dans les spam :-p
